### ISSUE TITLE
Run scheduled task as SYSTEM instead of user account

### ISSUE THREAD

**Issue by teconmoon** [BlackDragonBE/GPDWin2XTUManager#1]
Hi there, thanks for this tool. Pretty neat and drastically de-complicates XTU tweaking. I have some feedback regarding how it runs at startup.

When you run the program and check the box to set an XTU profile at startup, it only does it for when the current user logs in, not at system startup.

I tweaked the task created with Task Scheduler so that it runs as SYSTEM during startup, instead of running as the user account upon login used to open the tool initially.

The reason I did this is because I setup my GPD to autologin with a non-elevated local account, which has a game organization tool called Playnite set as the custom shell. I still have my Microsoft Account available for when I need to make changes as an administrator. But this makes it so that I don't have to do anything at startup, even for a non-elevated user.

Here's an example of the tweaked task XML. Thanks for reading! (.txt extension appended so I could upload it here)

[GPDWin2XTUManager.xml.txt](https://github.com/BlackDragonBE/GPDWin2XTUManager/files/2916720/GPDWin2XTUManager.xml.txt)

**Comment by BlackDragonBE** [comment]
@teconmoon 
Thanks! That's a great suggestion, I'll see if I can make that work in the next version.

Cheers!

**Comment by teconmoon** [comment]
Quick fyi I had to add a 30 second delay for the task, without it the task would still report as running successfully but the changes wouldn't consistently take hold (possibly it was running too soon after startup)

**Comment by BlackDragonBE** [comment]
@teconmoon I finally got around to implementing your suggestion! The XML you posted made it easy to pinpoint what I needed to change to make that happen.
I've committed the changes in 7a05a05, but I'll need to do some testing before I can release the next version. Thanks again for the tip!

**Comment by BlackDragonBE** [comment]
I've finally uploaded a new version. It's been a while since I used the GPD Win 2 for gaming. :)
