### ISSUE TITLE
Not recognized xtu

### ISSUE THREAD

**Issue by myfire888** [BlackDragonBE/GPDWin2XTUManager#2]
I have installed xtu. Then when i open ur manager it said "the intel extreme tuning utility couldn't be found. Open download page?"
I have run your manager with run as admin and still the same.
Anything i did wrong?

**Comment by myfire888** [comment]
For more info, i have disabled xtu and dptf on bios as well

**Comment by BlackDragonBE** [comment]
@myfire888 
The app checks if this executable exists:

C:\Program Files (x86)\Intel\Intel(R) Extreme Tuning Utility\Client\xtucli.exe

Can you try removing XTU and re-installing it, making sure to install it to "C:\Program Files (x86)\Intel\Intel(R) Extreme Tuning Utility"?

**Comment by myfire888** [comment]
Hi.
I found the folder. It was installed to the same directory
But instead of xtucli.exe, the folder only contain xtuUiLauncher.exe
Maybe different version?

I downloaded from here : https://downloadcenter.intel.com/download/24075/Intel-Extreme-Tuning-Utility-Intel-XTU-

And the version is 6.5.1.321
Maybe i should find lower version?

**Comment by myfire888** [comment]
I tried to just rename the exe to xtucli.exe. now ur program run but then it makes the xtu error all the time (something about illegal characters found in profile name may only contain "-" etc)

**Comment by BlackDragonBE** [comment]
@myfire888 
I just found out what's going on. The newest version of XTU that was released 6 days ago has removed the xtucli.exe for some reason.
See this thread on Reddit: https://www.reddit.com/r/gpdwin/comments/bbxgoz/beware_of_the_new_xtu_update/

I'll see if I can upload the old XTU setup on here and add another entry to the FAQ.

Thanks!

**Comment by myfire888** [comment]
Ok. I'll wait for u.thx

**Comment by BlackDragonBE** [comment]
@myfire888 

Here's the link to the old installer: https://github.com/BlackDragonBE/GPDWin2XTUManager/blob/master/XTU_Installer/XTU-Setup-6.4.1.25.exe

Completely remove your current XTU installation and install that one instead.
