### ISSUE TITLE
program hangs whenever i try to load a profile

### ISSUE THREAD

**Issue by xemnes** [BlackDragonBE/GPDWin2XTUManager#4]
not much else to say about this issue. whenever i click on a profile to load it, it says its applying the profile, my cursor flashes the loading wheel constantly the the program just becomes unresponsive forvever. ive ran the program as administrator

https://i.imgur.com/HC1e3pS.gifv

**Comment by BlackDragonBE** [comment]
Hi! I've noticed you're trying to set the minimum wattage to 55 and the maximum to 15. XTU won't apply those profiles as it would instantly fry your CPU. XTU Manager won't stop trying to reapply the profile until the values are set, so it freezes.
Valid values for wattages are between 1 & 15. I wouldn't undervolt more than about 75mV either.

Try deleting the Settings.json file next to the program's exe and start the program again. Do the stock values say 7, 15, 0 & 0?

For a good profile that mixes performance with battery try these settings:
- Minimum Watt: 4.5
- Maxiumum Watt: 8.5
- CPU Undervolt: -60mV
- GPU Undervolt: -60mV

Let me know if that helps!

Cheers,
Eric

**Comment by xemnes** [comment]
thanks for the response, well im undervolting at -155 as i want to improve the thermals. its the most lowest and stable undervolt i can reach without instability after extensive testing. 
im not sure why those profiles were there as they were there when i loaded the program.
ive deleted the json fille now and used your settings to test and it still hangs, looking at xtu though it does seem to apply the profile even though it forever hangs. however the error message i was experiencing in my other issue is gone.

**Comment by BlackDragonBE** [comment]
What version of the GPD Win 2 do you have? Can you check the processor type by opening the start menu, typing "msinfo32" and pressing enter?
Are you saying it eventually applies the profile or is the app still trying to do so endlessly?

**Comment by xemnes** [comment]
not sure what gpd win 2 is, i just downloaded your program as it seems to do what i want it to which is apply xtu profiles on startup (i cant find anything remotely similar, your program came up in a google search when trying to find something similar).
my processor is an i7 8850h
the program hangs forever but it does appear to apply the profile regardless

**Comment by BlackDragonBE** [comment]
Oh wow, I'm surprised it even worked in that case. This application is specifically designed for the GPD Win 2, a small handheld gaming laptop: http://gpd.hk/gdpwin2
It won't work with other processors and graphics cards unfortunately, I'm sorry about that.

**Comment by xemnes** [comment]
oh thats a shame :( seemed like the only program that could do what i need. ah well, thanks for helping me though.
